import { useMemo } from 'react';
import { Link, useLocation } from 'wouter';
import { ArrowUpRight, BookOpen, Check, ChevronRight, Clock3, Heart, Lightbulb, MessageCircle, ShieldCheck, ShoppingBag, Sparkles, Target } from 'lucide-react';
import { useGetDashboardSummary, useGetRecentActivity, getGetDashboardSummaryQueryKey, getGetRecentActivityQueryKey } from '@workspace/api-client-react';
import { Card, DemoPill, EmptyState, SectionTitle, Skeleton, Button } from '@/components/ui-core';
import { storage, timeAgo } from '@/lib/storage';

const actionCards = [
  { href: '/market', icon: ShoppingBag, label: 'Sense-check an item', detail: 'Know if the price feels right before you buy.', color: 'bg-primary/10 text-primary' },
  { href: '/study', icon: BookOpen, label: 'Learn something clearly', detail: 'Turn a fuzzy topic into a useful mental model.', color: 'bg-accent/15 text-accent-foreground' },
  { href: '/assistant', icon: MessageCircle, label: 'Think it through', detail: 'A grounded second perspective, on demand.', color: 'bg-secondary text-secondary-foreground' },
  { href: '/safehelp', icon: ShieldCheck, label: 'Find a safe next step', detail: 'Practical support for a difficult moment.', color: 'bg-chart-3/15 text-foreground' },
];

export default function Dashboard() {
  const [, setLocation] = useLocation();
  const summaryQuery = useGetDashboardSummary({ query: { queryKey: getGetDashboardSummaryQueryKey(), staleTime: 30_000 } });
  const activityQuery = useGetRecentActivity({ query: { queryKey: getGetRecentActivityQueryKey(), staleTime: 30_000 } });
  const summary = summaryQuery.data ?? { topicsLearned: storage.studies().length, practiceSessions: 4, savedItems: storage.favorites().length, planProgress: 42 };
  const activity = useMemo(() => activityQuery.data ?? [], [activityQuery.data]);
  const localActivities = storage.markets().slice(0, 3).map((m) => ({ id: m.id, type: 'market', title: m.title, detail: 'Market sense-check saved', time: timeAgo(m.createdAt) }));
  const visibleActivity = [...activity, ...localActivities].slice(0, 5);
  const iconFor = (type: string) => type === 'market' ? ShoppingBag : type === 'study' ? BookOpen : type === 'safehelp' ? ShieldCheck : type === 'plan' ? Target : MessageCircle;
  return <div className="animate-rise-in space-y-9">
    <section className="relative overflow-hidden rounded-[28px] bg-sidebar p-7 text-sidebar-foreground shadow-xl shadow-sidebar/10 md:p-10"><div className="dot-grid absolute inset-0 opacity-40" /><div className="absolute -right-16 -top-24 size-72 rounded-full bg-sidebar-primary/10 blur-3xl" /><div className="relative max-w-3xl"><DemoPill /><p className="mt-5 font-mono text-xs uppercase tracking-[.18em] text-sidebar-foreground/45">Tuesday, 14 May · your cockpit is ready</p><h1 className="mt-3 max-w-2xl font-serif text-4xl font-extrabold leading-[1.04] tracking-tight md:text-6xl">Make room for better <span className="text-sidebar-primary">next steps.</span></h1><p className="mt-5 max-w-xl text-base leading-relaxed text-sidebar-foreground/65">AI LifeHub keeps the useful parts of thinking close: a clearer decision, a stronger understanding, a safer way forward.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/assistant" data-testid="link-dashboard-assistant" className="inline-flex items-center gap-2 rounded-xl bg-sidebar-primary px-4 py-3 text-sm font-bold text-sidebar-primary-foreground hover:-translate-y-0.5">Start a thought <ArrowUpRight size={16} /></Link><Link href="/study" data-testid="link-dashboard-study" className="inline-flex items-center gap-2 rounded-xl border border-sidebar-border px-4 py-3 text-sm font-bold text-sidebar-foreground hover:bg-sidebar-accent">Continue learning <ChevronRight size={16} /></Link></div></div><div className="absolute bottom-7 right-8 hidden h-28 w-48 rounded-2xl border border-sidebar-border bg-sidebar-accent/50 p-4 lg:block"><div className="flex items-center justify-between"><span className="font-mono text-[9px] uppercase tracking-widest text-sidebar-foreground/45">Focus signal</span><span className="size-2 rounded-full bg-sidebar-primary animate-breathe" /></div><div className="mt-5 flex items-end gap-1.5"><div className="h-7 w-2 rounded-full bg-sidebar-primary/35" /><div className="h-11 w-2 rounded-full bg-sidebar-primary/60" /><div className="h-8 w-2 rounded-full bg-sidebar-primary/45" /><div className="h-16 w-2 rounded-full bg-sidebar-primary" /><div className="h-12 w-2 rounded-full bg-sidebar-primary/70" /><div className="h-20 w-2 rounded-full bg-sidebar-primary/80" /><div className="h-10 w-2 rounded-full bg-sidebar-primary/45" /></div></div></section>
    <section><SectionTitle eyebrow="A quick read" title="Your momentum" detail="Small signals from the things you have been working through." /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[{ label: 'Topics learned', value: summary.topicsLearned, Icon: BookOpen, note: 'this month' }, { label: 'Practice sessions', value: summary.practiceSessions, Icon: Check, note: 'keep the rhythm' }, { label: 'Saved decisions', value: summary.savedItems, Icon: Heart, note: 'worth revisiting' }, { label: 'Plan progress', value: `${summary.planProgress}%`, Icon: Target, note: 'steady is good' }].map(({ label, value, Icon, note }, index) => <Card key={label} className="group relative overflow-hidden p-5"><div className="flex items-start justify-between"><span className="rounded-xl bg-secondary p-2.5 text-primary"><Icon size={17} /></span><span className="font-mono text-[10px] text-muted-foreground">0{index + 1}</span></div><p data-testid={`text-stat-${label.toLowerCase().replaceAll(' ', '-')}`} className="mt-5 font-serif text-3xl font-extrabold">{value}</p><p className="mt-1 text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p><div className="absolute -bottom-10 -right-10 size-24 rounded-full bg-primary/5 transition-transform group-hover:scale-150" /></Card>)}</div></section>
    <section><SectionTitle eyebrow="Choose your lane" title="What would help right now?" /><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4">{actionCards.map(({ href, icon: Icon, label, detail, color }) => <Link href={href} key={href} data-testid={`link-quick-${href.slice(1)}`} className="group rounded-2xl border border-border bg-card p-5 shadow-sm hover:-translate-y-1 hover:border-primary/35 hover:shadow-lg"><span className={`inline-flex rounded-xl p-2.5 ${color}`}><Icon size={19} /></span><h3 className="mt-5 font-serif text-lg font-extrabold">{label}</h3><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{detail}</p><span className="mt-5 inline-flex items-center gap-1 text-xs font-bold text-primary">Open tool <ArrowUpRight size={14} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></span></Link>)}</div></section>
    <section className="grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><Card className="p-6"><SectionTitle eyebrow="The thread so far" title="Recent activity" action={<Link href="/history" data-testid="link-view-history" className="text-xs font-bold text-primary">View timeline <ArrowUpRight size={13} className="ml-1 inline" /></Link>} />{activityQuery.isLoading ? <div className="space-y-4"><Skeleton className="h-12" /><Skeleton className="h-12" /><Skeleton className="h-12" /></div> : visibleActivity.length ? <div className="space-y-1">{visibleActivity.map((item) => { const Icon = iconFor(item.type); return <div data-testid={`activity-item-${item.id}`} key={item.id} className="flex items-center gap-3 rounded-xl p-3 hover:bg-muted/60"><span className="rounded-xl bg-secondary p-2.5 text-primary"><Icon size={16} /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{item.title}</p><p className="truncate text-xs text-muted-foreground">{item.detail}</p></div><span className="whitespace-nowrap font-mono text-[10px] text-muted-foreground">{item.time.includes('ago') ? item.time : timeAgo(item.time)}</span></div>})}</div> : <EmptyState icon={Clock3} title="Your timeline starts here" detail="Use a tool above and the useful trail will appear in this space." />}</Card><Card className="relative overflow-hidden bg-secondary p-6"><div className="absolute -right-12 -top-12 size-40 rounded-full bg-accent/20" /><div className="relative"><span className="inline-flex rounded-xl bg-card p-2.5 text-accent-foreground"><Lightbulb size={18} /></span><h3 className="mt-5 font-serif text-2xl font-extrabold">A gentler pace is still progress.</h3><p className="mt-3 text-sm leading-relaxed text-secondary-foreground/70">You do not need a perfect plan. Pick one useful question and give it ten focused minutes.</p><Button data-testid="button-daily-nudge" variant="primary" className="mt-6" onClick={() => setLocation('/study')}>Give me a ten-minute topic <ArrowUpRight size={15} /></Button></div></Card></section>
  </div>;
}