import { type FormEvent, useRef, useState } from 'react';
import { ArrowLeft, Check, CircleDollarSign, FileSearch, Heart, ImagePlus, Info, LoaderCircle, RotateCcw, ScanSearch, ShoppingBag, Tag, UploadCloud } from 'lucide-react';
import { useAnalyzeMarketItem, type MarketAnalysis, type MarketAnalysisInputCurrency, MarketAnalysisInputCurrency as Currencies } from '@workspace/api-client-react';
import { Button, Card, DemoPill, EmptyState, Field, SectionTitle } from '@/components/ui-core';
import { storage, uid } from '@/lib/storage';

const listings = [
  { title: 'Sony WH-1000XM4 headphones', price: '$168', note: 'Good condition · 12 watchers', tone: 'bg-chart-4/15' },
  { title: 'Herman Miller Sayl chair', price: '$430', note: 'Very good · local pickup', tone: 'bg-primary/10' },
  { title: 'Fujifilm X-T30 II body', price: '$690', note: 'Like new · includes strap', tone: 'bg-accent/15' },
];

export default function Market() {
  const [title, setTitle] = useState('');
  const [price, setPrice] = useState('');
  const [currency, setCurrency] = useState<MarketAnalysisInputCurrency>('USD');
  const [imageName, setImageName] = useState<string | null>(null);
  const [result, setResult] = useState<MarketAnalysis | null>(null);
  const [saved, setSaved] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const analyze = useAnalyzeMarketItem({ mutation: { onSuccess: (data) => { setResult(data); storage.saveMarkets([{ id: uid(), title: title || data.model, createdAt: new Date().toISOString(), price: Number(price), currency, imageName, result: data }, ...storage.markets()]); } } });
  const submit = (event: FormEvent) => { event.preventDefault(); if (!title.trim() || !price) return; analyze.mutate({ data: { title: title.trim(), price: Number(price), currency, imageName } }); };
  const toggleSave = () => { if (!result) return; const key = `${result.brand}-${result.model}`; const favorites = storage.favorites(); const next = favorites.includes(key) ? favorites.filter((x) => x !== key) : [...favorites, key]; storage.saveFavorites(next); setSaved(!favorites.includes(key)); };
  return <div className="animate-rise-in space-y-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[.18em] text-primary"><ShoppingBag size={13} /> Market sense</div><h1 className="font-serif text-4xl font-extrabold tracking-tight md:text-5xl">Buy with a clearer read.</h1><p className="mt-2 max-w-xl text-muted-foreground">A calm second opinion for the things you find in the wild. AI LifeHub compares context, condition, and price — not just a product title.</p></div><DemoPill /></div>
    <div className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><Card className="p-6"><SectionTitle eyebrow="01 / Add an item" title="What are you considering?" detail="A title and price are enough to start. A photo makes the read more specific." /><form onSubmit={submit} className="space-y-5"><Field data-testid="input-market-title" label="Listing title" placeholder="e.g. Apple MacBook Air M2, 2022" value={title} onChange={(e) => setTitle(e.target.value)} required /><div className="grid grid-cols-[1fr_112px] gap-3"><Field data-testid="input-market-price" label="Seller price" type="number" min="0" step="0.01" placeholder="0.00" value={price} onChange={(e) => setPrice(e.target.value)} required /><label className="block space-y-1.5"><span className="text-xs font-bold uppercase tracking-[.12em] text-muted-foreground">Currency</span><select data-testid="select-market-currency" value={currency} onChange={(e) => setCurrency(e.target.value as MarketAnalysisInputCurrency)} className="w-full rounded-xl border border-input bg-background/75 px-3.5 py-3 text-sm">{Object.values(Currencies).map((item) => <option key={item} value={item}>{item}</option>)}</select></label></div><button data-testid="button-upload-market-image" type="button" onClick={() => fileRef.current?.click()} className="flex w-full items-center gap-3 rounded-xl border border-dashed border-input bg-muted/30 p-4 text-left hover:border-primary hover:bg-primary/5"><span className="rounded-xl bg-secondary p-2.5 text-primary"><ImagePlus size={19} /></span><span><span className="block text-sm font-bold">{imageName ?? 'Add a listing photo'}</span><span className="block text-xs text-muted-foreground">{imageName ? 'Ready to include in your analysis' : 'Optional · JPG, PNG up to 10MB'}</span></span><UploadCloud size={16} className="ml-auto text-muted-foreground" /></button><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={(e) => setImageName(e.target.files?.[0]?.name ?? null)} /><Button data-testid="button-analyze-market" type="submit" disabled={analyze.isPending || !title || !price} className="w-full">{analyze.isPending ? <><LoaderCircle size={16} className="animate-spin" /> Reading the signals…</> : <><ScanSearch size={16} /> Analyze this item</>}</Button>{analyze.isError && <p data-testid="status-market-error" className="rounded-xl bg-destructive/10 p-3 text-xs text-destructive">The demo reader hit a snag. Check the details and try again.</p>}</form></Card>
      <Card className="min-h-[520px] overflow-hidden p-6">{result ? <Result result={result} saved={saved} onSave={toggleSave} onReset={() => setResult(null)} /> : <EmptyState icon={FileSearch} title="Your read will land here" detail="Enter a listing on the left to see a practical price range, confidence, and the details worth checking before you message the seller." action={<div className="flex items-center gap-2 text-xs text-muted-foreground"><Info size={14} /> Demo results are clearly marked</div>} />}</Card></div>
    <section><SectionTitle eyebrow="Pattern library" title="Similar demo listings" detail="A little context makes a number more useful." /><div className="grid gap-3 md:grid-cols-3">{listings.map((item, index) => <button data-testid={`button-listing-${index}`} key={item.title} onClick={() => { setTitle(item.title); setPrice(item.price.replace('$', '')); setCurrency('USD'); }} className={`rounded-2xl border border-border p-5 text-left shadow-sm transition hover:-translate-y-1 hover:border-primary/30 ${item.tone}`}><div className="flex h-24 items-center justify-center rounded-xl border border-border/50 bg-card/45"><Tag size={27} className="text-primary/70" /></div><p className="mt-4 font-serif text-base font-extrabold">{item.title}</p><p className="mt-1 font-mono text-lg font-bold text-primary">{item.price}</p><p className="mt-1 text-xs text-muted-foreground">{item.note}</p></button>)}</div></section>
  </div>;
}

function Result({ result, saved, onSave, onReset }: { result: MarketAnalysis; saved: boolean; onSave: () => void; onReset: () => void }) {
  const verdict = result.verdict === 'good' ? { label: 'Worth a closer look', tone: 'bg-primary/12 text-primary', icon: Check } : result.verdict === 'fair' ? { label: 'Fair, with questions', tone: 'bg-chart-3/15 text-foreground', icon: Info } : { label: 'Price feels ambitious', tone: 'bg-accent/15 text-accent-foreground', icon: CircleDollarSign };
  const VerdictIcon = verdict.icon;
  return <div className="animate-rise-in"><div className="flex items-start justify-between gap-3"><div><div className="mb-2 flex items-center gap-2"><span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-bold ${verdict.tone}`}><VerdictIcon size={14} /> {verdict.label}</span><DemoPill /></div><h2 className="font-serif text-2xl font-extrabold">{result.brand} {result.model}</h2><p className="mt-1 text-sm text-muted-foreground">{result.category} · {result.condition}</p></div><button data-testid="button-save-market" onClick={onSave} className={`rounded-xl p-2.5 ${saved ? 'bg-accent/20 text-accent-foreground' : 'bg-secondary text-muted-foreground hover:text-accent-foreground'}`}><Heart size={18} fill={saved ? 'currentColor' : 'none'} /></button></div><div className="mt-7 rounded-2xl bg-sidebar p-5 text-sidebar-foreground"><div className="flex items-end justify-between"><div><p className="font-mono text-[10px] uppercase tracking-widest text-sidebar-foreground/50">Estimated market range</p><p className="mt-2 font-serif text-3xl font-extrabold">{result.currency} {result.estimatedPriceMin}–{result.estimatedPriceMax}</p></div><div className="text-right"><p className="font-mono text-[10px] uppercase tracking-widest text-sidebar-foreground/50">Confidence</p><p className="mt-2 font-serif text-2xl font-bold text-sidebar-primary">{result.confidence}%</p></div></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-sidebar-accent"><div className="h-full rounded-full bg-sidebar-primary" style={{ width: `${result.confidence}%` }} /></div></div><p className="mt-5 text-sm leading-relaxed text-muted-foreground">{result.description}</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><div><h3 className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider"><FileSearch size={14} className="text-primary" /> Check before buying</h3><ul className="mt-3 space-y-2">{result.thingsToCheck.map((thing) => <li key={thing} className="flex gap-2 text-sm text-muted-foreground"><span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-accent" />{thing}</li>)}</ul></div><div className="rounded-xl bg-secondary/65 p-4"><p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Seller asks</p><p className="mt-1 font-serif text-2xl font-extrabold">{result.currency} {result.sellerPrice}</p><p className={`mt-1 text-xs font-bold ${result.difference >= 0 ? 'text-primary' : 'text-accent-foreground'}`}>{result.difference >= 0 ? `${result.difference}% below the useful range` : `${Math.abs(result.difference)}% above the useful range`}</p></div></div><div className="mt-7 flex flex-wrap gap-2"><Button data-testid="button-market-reset" variant="secondary" onClick={onReset}><RotateCcw size={15} /> New item</Button><Button data-testid="button-market-favorite" variant="ghost" onClick={onSave}><Heart size={15} fill={saved ? 'currentColor' : 'none'} /> {saved ? 'Saved to your hub' : 'Save this read'}</Button></div></div>;
}